### ISSUE TITLE
License

### ISSUE THREAD

**Issue by narknon** [OutTheShade/UnrealMappingsDumper#3]
Hi there, thanks for the dumper.

Would you be able to add a license?  Also, any interest in having the writer added to an existing hook that can hook into a large number of games?

**Comment by OutTheShade** [comment]
Just added the license, thanks for the reminder. Still kinda curious as to what you by mean your second question though. Could you be more precise?

**Comment by UE4SS** [comment]
What he wishes for is for your tool, one way or another, to work with a game that it currently doesn't work with.

That game is using a customized UE 4.18 with backported unversioned properties.

Originally he thought of having your tool ported to UE4SS's backend API because it's compatible with his game.
I think that it may be better and easier if you can add support for his game to your tool directly instead.
I can also share my AOBs (GUObjectArray/FName sig) but it's not entirely clear to me what part of your tool is incompatible with his game.

**Comment by OutTheShade** [comment]
The dumper is designed to work on as many games as possible, mainly on UE5 and versions close to it

4.18 is pretty far back and I can almost guarantee it's due to a different in the core types. 

Odds are this engine version is using UProperties as well, so even if the types matched, the way the usmap is generated would have to be refactored. 

I'm currently busy with some other projects, but if you can send me a place to download this game, I'll see what I can do when I get the chance. No guarantees though, considering this is a pretty special case.

**Comment by OutTheShade** [comment]
Though I am curious why you backported unversioned properties to your game instead of just using a newer engine version lol

**Comment by nReCon** [comment]
> Though I am curious why you backported unversioned properties to your game instead of just using a newer engine version lol

We're not talking about a game that I or narknon created but a game that someone else created and the developer for whatever reason did all sorts of engine customization.
I have no idea why they did that, but I'm sure they had their reasons.

**Comment by UE4SS** [comment]
> Though I am curious why you backported unversioned properties to your game instead of just using a newer engine version lol

We're not talking about a game that I or narknon created but a game that someone else created and the developer for whatever reason did all sorts of engine customization.
I have no idea why they did that, but I'm sure they had their reasons.

**Comment by OutTheShade** [comment]
Ah I see I misinterpreted your comment lol. But yeah it would help to at least tell me the name of the game

**Comment by narknon** [comment]
It's Final Fantasy 7 Remake.  When they ported it to PS5/PC, Epic talked them into using unversioned properties to help with file size/load time a bit.

**Comment by OutTheShade** [comment]
I'll take a look at it when I get the chance. Thanks for letting me know
